image: gradle:jdk8

before_script:
  - wget -q https://courses.cs.washington.edu/courses/cse373/18au/files/hw_scripts/hw4-build-gradle -O build.gradle

stages:
  - compile
  - test

Compile:
  stage: compile
  script:
    - wget -q https://courses.cs.washington.edu/courses/cse373/18au/files/hw_scripts/hw4-compile.sh
    - sh hw4-compile.sh
  tags:
    - compile


DoubleLinkedlist:
  stage: test
  script:
    - wget -q https://courses.cs.washington.edu/courses/cse373/18au/files/hw_scripts/hw4-dll.sh
    - sh hw4-dll.sh
  tags:
    - testdll


HashDictionary:
  stage: test
  script:
    - wget -q https://courses.cs.washington.edu/courses/cse373/18au/files/hw_scripts/hw4-hash.sh
    - sh hw4-hash.sh
  tags:
    - testhash


IsValidAVL:
  stage: test
  script:
    - wget -q https://courses.cs.washington.edu/courses/cse373/18au/files/hw_scripts/hw4-avltest.sh
    - sh hw4-avltest.sh
  tags:
    - testavl


StyleCheck:
  stage: test
  script:
    - wget -q https://courses.cs.washington.edu/courses/cse373/18au/files/hw_scripts/hw4-stylecheck.sh
    - sh hw4-stylecheck.sh
  tags:
    - stylecheck
